import { ReceiverType } from "../utils/common";
export declare class User {
    uid: string;
    name: string;
    avatar?: string;
    status?: string;
    metadata?: Record<string, any>;
    constructor(uid: string, name: string);
    getUid(): string;
    getName(): string;
    getAvatar(): string | undefined;
    getStatus(): string | undefined;
    getMetadata(): Record<string, any> | undefined;
    setAvatar(avatar: string): void;
    setStatus(status: string): void;
    setMetadata(metadata: Record<string, any>): void;
}
declare class TextMessage {
    id: string;
    receiverId: string;
    senderId: string;
    senderName: string;
    text: string;
    sentAt: string;
    status: string;
    receiverType: ReceiverType;
    editedAt: string;
    editedBy: string;
    deletedAt: string;
    deletedBy: string;
    parentMessageId: string;
    replyToUserId: string;
    replyToText: string;
    replyType: string;
    private sender;
    private receiver;
    constructor(receiverId: string, text: string, receiverType?: ReceiverType);
    getId(): string;
    getReceiverId(): string;
    getSenderId(): string;
    getSenderName(): string;
    getText(): string;
    getSentAt(): string;
    getStatus(): string;
    getReceiverType(): ReceiverType;
    getEditedAt(): string;
    getEditedBy(): string;
    getDeletedAt(): string;
    getDeletedBy(): string;
    getParentMessageId(): string;
    getReplyToUserId(): string;
    getReplyToText(): string;
    getReplyType(): string;
    getSender(): User | null;
    getReceiver(): User | null;
    _setId(id: string): void;
    _setSenderId(senderId: string): void;
    _setSenderName(senderName: string): void;
    _setSentAt(sentAt: string): void;
    _setStatus(status: string): void;
    _setEditedAt(editedAt: string): void;
    _setEditedBy(editedBy: string): void;
    _setDeletedAt(deletedAt: string): void;
    _setDeletedBy(deletedBy: string): void;
    _setParentMessageId(parentMessageId: string): void;
    _setReplyToUserId(replyToUserId: string): void;
    _setReplyToText(replyToText: string): void;
    _setReplyType(replyType: string): void;
    setText(text: string): void;
    setId(id: string): void;
    setParentMessageId(parentMessageId: string): void;
    setReplyToUserId(replyToUserId: string): void;
    setReplyToText(replyToText: string): void;
    setReplyType(replyType: string): void;
    _setSender(sender: User): void;
    _setReceiver(receiver: User): void;
}
export default TextMessage;
